version: '3'
services:
    node:
        build:
            context: .
        image: react-ts__img
        container_name: react-ts__con
        tty: true
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/usr/src/app
        # command: sh -c "cd sample_app && yarn start"
        ports:
            - "3000:3000"
